### ISSUE TITLE
Tools Its not Working Correctly 

### ISSUE THREAD

**Issue by lbmaster23** [rvost/DayzServerTools#3] opened 2024-05-08 02:20 UTC
The Tools its Not loading Category Value Flagas Usage Flags or Tags
![image](https://github.com/rvost/DayzServerTools/assets/51199528/17b2cec8-3861-4bee-aed0-1124a9714c14)

**Comment by rvost** [comment] 2024-05-19 19:12
Can you please share your file (e.g. via [pastebin](https://pastebin.com/)) as I cannot reproduce the issue with any valid file.

P.S. Sorry for the late response.

**Comment by rvost** [comment] 2024-06-01 11:24
I'll close the issue for now. Feel free to reopen it with more info.

**Closed as completed by rvost** 2024-06-01 11:24 UTC
